# Generated by Django 6.1.1 on 2026-09-16 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Usada para organizar a orden de prioridade.', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Prioridade',
                'verbose_name_plural': 'Prioridades',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Em Atendimento'), ('FECHADO', 'Concluído')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_limite', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Prazo limite (SLA)')),
                ('data_fechamento', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fechado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='core.categoria', verbose_name='Categoria')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='core.equipe', verbose_name='Equipe')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='core.prioridade', verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(help_text='Prazo limite de resolução.', verbose_name='Horas para atendimento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='core.categoria', verbose_name='Categoria')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='core.prioridade', verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
                'ordering': ['categoria', 'prioridade'],
                'unique_together': {('categoria', 'prioridade')},
            },
        ),
    ]
