# Generated by Django 6.1.1 on 2026-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("INCIDENTE", "Incidente"),
                    ("REQUISICAO", "Requisição"),
                    ("DUVIDA", "Dúvida"),
                ],
                default="INCIDENTE",
                max_length=12,
                verbose_name="Tipo",
            ),
        ),
    ]
